### ISSUE TITLE
Tracking Implementation Goals

### ISSUE THREAD

**Issue by SebastianAment** [MingChiangChang/CrystalShift.jl#7]
- [x] Make continuous integration work
   - [x] update dependencies (still missing: BackgroundSubtraction, OptimizationAlgorithms)
   - [x] ensure testing suite works
- [x] Saddle-point-free Newton optimization of KL divergence
   - [x] check convergence on synthetic data (is gradient small and Hessian p.s.d.?)
- [x] Background model 
   - [x] add background model to reconstruction
   - [x] add background model to optimization
- [x] Adding Pseudo-Voigt profile
   - [x] add profile to reconstruction
   - [x] add profile to optimization (needs `get_free_params`, etc.)
- [ ] Potentially need support for shifts in peak heights beyond what the code in crystalphase.jl allows. Some real data is messy.
- [x] Make activation prior penalize correct
    - [x] Normalize peak intensity of a phase when constructing the stick file from cif
    - [x] Store the normalization constant
    - [x] Implement function that extract the phase fraction from a phase combination

**Comment by MingChiangChang** [comment]
Update more goals.

**Comment by MingChiangChang** [comment]
Move the peak height modulation to an independent issue.
